// Auto-generated verified YouTube Shorts list from https://www.youtube.com/@asadlandholdings/shorts
export interface ShortVideoItem {
  id: string;
  videoId: string;
  title: string;
  cleanTitle: string;
  views: string;
  society: string;
  category: string;
  tag: string;
  duration: string;
  thumbnail: string;
  videoUrl: string;
  youtubeUrl: string;
  publishedDate: string;
  description: string;
  isShort: boolean;
  aspectRatio: "9:16";
  linkedSocietySlug?: string;
  linkedPropertyId?: string;
}

export const SHORTS_DATA: ShortVideoItem[] = [
  {
    "id": "short-1",
    "videoId": "XnVt9W1jOnA",
    "title": "Ghar bnanay ka Asli tareeka #realestateinvestment",
    "cleanTitle": "Ghar bnanay ka Asli tareeka",
    "views": "1.7K views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/XnVt9W1jOnA/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/XnVt9W1jOnA",
    "youtubeUrl": "https://www.youtube.com/shorts/XnVt9W1jOnA",
    "publishedDate": "2026",
    "description": "Ghar bnanay ka Asli tareeka. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-2",
    "videoId": "gaMp8d1vP6A",
    "title": "Foundation work completed #realestateinvestment",
    "cleanTitle": "Foundation work completed",
    "views": "1.2K views",
    "society": "Wah Cantt",
    "category": "CONSTRUCTION_TIPS",
    "tag": "Construction & Engineering",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/gaMp8d1vP6A/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/gaMp8d1vP6A",
    "youtubeUrl": "https://www.youtube.com/shorts/gaMp8d1vP6A",
    "publishedDate": "2026",
    "description": "Foundation work completed. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-3",
    "videoId": "jLltM5-boiA",
    "title": "Concrete spacers #realestateinvestment",
    "cleanTitle": "Concrete spacers",
    "views": "1.6K views",
    "society": "Wah Cantt",
    "category": "CONSTRUCTION_TIPS",
    "tag": "Construction & Engineering",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/jLltM5-boiA/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/jLltM5-boiA",
    "youtubeUrl": "https://www.youtube.com/shorts/jLltM5-boiA",
    "publishedDate": "2026",
    "description": "Concrete spacers. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-4",
    "videoId": "jfEM7VUV1H0",
    "title": "Protection from wall dampness #realestateinvestment",
    "cleanTitle": "Protection from wall dampness",
    "views": "2.1K views",
    "society": "Wah Cantt",
    "category": "CONSTRUCTION_TIPS",
    "tag": "Construction & Engineering",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/jfEM7VUV1H0/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/jfEM7VUV1H0",
    "youtubeUrl": "https://www.youtube.com/shorts/jfEM7VUV1H0",
    "publishedDate": "2026",
    "description": "Protection from wall dampness. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-5",
    "videoId": "7yK6i9NI9vI",
    "title": "Ghar ko saim se kese bacha jaye #realestateinvestment",
    "cleanTitle": "Ghar ko saim se kese bacha jaye",
    "views": "3.8K views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/7yK6i9NI9vI/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/7yK6i9NI9vI",
    "youtubeUrl": "https://www.youtube.com/shorts/7yK6i9NI9vI",
    "publishedDate": "2026",
    "description": "Ghar ko saim se kese bacha jaye. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-6",
    "videoId": "OEIzcAQVgmo",
    "title": "Ase karo kam #realestateinvestment",
    "cleanTitle": "Ase karo kam",
    "views": "592 views",
    "society": "Wah Cantt",
    "category": "ADVISORY",
    "tag": "Real Estate",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/OEIzcAQVgmo/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/OEIzcAQVgmo",
    "youtubeUrl": "https://www.youtube.com/shorts/OEIzcAQVgmo",
    "publishedDate": "2026",
    "description": "Ase karo kam. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-7",
    "videoId": "aCLG6l3kr5U",
    "title": "Concept house #realestateinvestment",
    "cleanTitle": "Concept house",
    "views": "4.5K views",
    "society": "Wah Cantt",
    "category": "ADVISORY",
    "tag": "Real Estate",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/aCLG6l3kr5U/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/aCLG6l3kr5U",
    "youtubeUrl": "https://www.youtube.com/shorts/aCLG6l3kr5U",
    "publishedDate": "2026",
    "description": "Concept house. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-8",
    "videoId": "bgPeSHCcMxs",
    "title": "Ye kam krne ka sahi tareeqa hota hai #realestateinvestment",
    "cleanTitle": "Ye kam krne ka sahi tareeqa hota hai",
    "views": "2.5K views",
    "society": "Wah Cantt",
    "category": "ADVISORY",
    "tag": "Real Estate",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/bgPeSHCcMxs/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/bgPeSHCcMxs",
    "youtubeUrl": "https://www.youtube.com/shorts/bgPeSHCcMxs",
    "publishedDate": "2026",
    "description": "Ye kam krne ka sahi tareeqa hota hai. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-9",
    "videoId": "UbVSVh3IMDk",
    "title": "Best time to buy plot #realestateinvestment",
    "cleanTitle": "Best time to buy plot",
    "views": "1.1K views",
    "society": "Wah Cantt",
    "category": "PLOT_SALE",
    "tag": "Plot Deal",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/UbVSVh3IMDk/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/UbVSVh3IMDk",
    "youtubeUrl": "https://www.youtube.com/shorts/UbVSVh3IMDk",
    "publishedDate": "2026",
    "description": "Best time to buy plot. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-10",
    "videoId": "tBAE4b5MPWQ",
    "title": "Choti ghalti ziada nuqsan #realestateinvestment",
    "cleanTitle": "Choti ghalti ziada nuqsan",
    "views": "4.7K views",
    "society": "Wah Cantt",
    "category": "ADVISORY",
    "tag": "Market Advisory",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/tBAE4b5MPWQ/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/tBAE4b5MPWQ",
    "youtubeUrl": "https://www.youtube.com/shorts/tBAE4b5MPWQ",
    "publishedDate": "2026",
    "description": "Choti ghalti ziada nuqsan. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-11",
    "videoId": "IvVQgFS8dW0",
    "title": "House for sale in Wah cantt #realestateinvestment",
    "cleanTitle": "House for sale in Wah cantt",
    "views": "1.4K views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/IvVQgFS8dW0/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/IvVQgFS8dW0",
    "youtubeUrl": "https://www.youtube.com/shorts/IvVQgFS8dW0",
    "publishedDate": "2026",
    "description": "House for sale in Wah cantt. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-12",
    "videoId": "xw9w52IqKTc",
    "title": "Cheap house for sale in Kohistan enclave #realestateinvestment",
    "cleanTitle": "Cheap house for sale in Kohistan enclave",
    "views": "1.8K views",
    "society": "Kohistan Enclave",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/xw9w52IqKTc/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/xw9w52IqKTc",
    "youtubeUrl": "https://www.youtube.com/shorts/xw9w52IqKTc",
    "publishedDate": "2026",
    "description": "Cheap house for sale in Kohistan enclave. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-13",
    "videoId": "ESq0KzmA3kQ",
    "title": "House for sale in Kohistan enclave #realestateinvestment",
    "cleanTitle": "House for sale in Kohistan enclave",
    "views": "3.1K views",
    "society": "Kohistan Enclave",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/ESq0KzmA3kQ/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/ESq0KzmA3kQ",
    "youtubeUrl": "https://www.youtube.com/shorts/ESq0KzmA3kQ",
    "publishedDate": "2026",
    "description": "House for sale in Kohistan enclave. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-14",
    "videoId": "OUNCqPBYUMI",
    "title": "Ghar ase bnty hain #realestateinvestment",
    "cleanTitle": "Ghar ase bnty hain",
    "views": "5.5K views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/OUNCqPBYUMI/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/OUNCqPBYUMI",
    "youtubeUrl": "https://www.youtube.com/shorts/OUNCqPBYUMI",
    "publishedDate": "2026",
    "description": "Ghar ase bnty hain. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-15",
    "videoId": "JxAcvXu2niI",
    "title": "Kohistan enclave extension 4 #realestateinvestment",
    "cleanTitle": "Kohistan enclave extension 4",
    "views": "1.2K views",
    "society": "Kohistan Enclave",
    "category": "ADVISORY",
    "tag": "Real Estate",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/JxAcvXu2niI/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/JxAcvXu2niI",
    "youtubeUrl": "https://www.youtube.com/shorts/JxAcvXu2niI",
    "publishedDate": "2026",
    "description": "Kohistan enclave extension 4. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-16",
    "videoId": "I1RQilMSayY",
    "title": "8 Marla house for sale in Kohistan enclave Wah cantt #househuntersinternational",
    "cleanTitle": "8 Marla house for sale in Kohistan enclave Wah cantt",
    "views": "1.4K views",
    "society": "Kohistan Enclave",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/I1RQilMSayY/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/I1RQilMSayY",
    "youtubeUrl": "https://www.youtube.com/shorts/I1RQilMSayY",
    "publishedDate": "2026",
    "description": "8 Marla house for sale in Kohistan enclave Wah cantt. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-17",
    "videoId": "ZlWoP4I7f7o",
    "title": "Ase kam kyun nai krty log #realestateinvestment",
    "cleanTitle": "Ase kam kyun nai krty log",
    "views": "2.6K views",
    "society": "Wah Cantt",
    "category": "ADVISORY",
    "tag": "Real Estate",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/ZlWoP4I7f7o/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/ZlWoP4I7f7o",
    "youtubeUrl": "https://www.youtube.com/shorts/ZlWoP4I7f7o",
    "publishedDate": "2026",
    "description": "Ase kam kyun nai krty log. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-18",
    "videoId": "v5stNm8qEI4",
    "title": "Plot kese khareedain #realestateinvestment",
    "cleanTitle": "Plot kese khareedain",
    "views": "1.2K views",
    "society": "Wah Cantt",
    "category": "PLOT_SALE",
    "tag": "Plot Deal",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/v5stNm8qEI4/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/v5stNm8qEI4",
    "youtubeUrl": "https://www.youtube.com/shorts/v5stNm8qEI4",
    "publishedDate": "2026",
    "description": "Plot kese khareedain. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-19",
    "videoId": "27ThtcJa2qE",
    "title": "8 Marla house for sale in Kohistan enclave #realestateinvestment",
    "cleanTitle": "8 Marla house for sale in Kohistan enclave",
    "views": "7.8K views",
    "society": "Kohistan Enclave",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/27ThtcJa2qE/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/27ThtcJa2qE",
    "youtubeUrl": "https://www.youtube.com/shorts/27ThtcJa2qE",
    "publishedDate": "2026",
    "description": "8 Marla house for sale in Kohistan enclave. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-20",
    "videoId": "uqzWcFelxfE",
    "title": "House for sale in Wah cantt #realestateinvestment",
    "cleanTitle": "House for sale in Wah cantt",
    "views": "666 views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/uqzWcFelxfE/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/uqzWcFelxfE",
    "youtubeUrl": "https://www.youtube.com/shorts/uqzWcFelxfE",
    "publishedDate": "2026",
    "description": "House for sale in Wah cantt. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-21",
    "videoId": "GIwlmNZOEUU",
    "title": "Ghar kese bnayein #realestateinvestment",
    "cleanTitle": "Ghar kese bnayein",
    "views": "1.2K views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/GIwlmNZOEUU/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/GIwlmNZOEUU",
    "youtubeUrl": "https://www.youtube.com/shorts/GIwlmNZOEUU",
    "publishedDate": "2026",
    "description": "Ghar kese bnayein. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-22",
    "videoId": "GG7pTj69KrI",
    "title": "Ghar ase bnao #realestateinvestment",
    "cleanTitle": "Ghar ase bnao",
    "views": "2.6K views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/GG7pTj69KrI/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/GG7pTj69KrI",
    "youtubeUrl": "https://www.youtube.com/shorts/GG7pTj69KrI",
    "publishedDate": "2026",
    "description": "Ghar ase bnao. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-23",
    "videoId": "y9nMM20YOTU",
    "title": "8.4 marla house for sale in Wah cantt #realestateinvestment",
    "cleanTitle": "8.4 marla house for sale in Wah cantt",
    "views": "1.5K views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/y9nMM20YOTU/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/y9nMM20YOTU",
    "youtubeUrl": "https://www.youtube.com/shorts/y9nMM20YOTU",
    "publishedDate": "2026",
    "description": "8.4 marla house for sale in Wah cantt. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-24",
    "videoId": "qVpJ1L0Fvkk",
    "title": "Barsaat ma construction krne ka tareeqa #realestateinvestment",
    "cleanTitle": "Barsaat ma construction krne ka tareeqa",
    "views": "1.6K views",
    "society": "Wah Cantt",
    "category": "CONSTRUCTION_TIPS",
    "tag": "Construction & Engineering",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/qVpJ1L0Fvkk/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/qVpJ1L0Fvkk",
    "youtubeUrl": "https://www.youtube.com/shorts/qVpJ1L0Fvkk",
    "publishedDate": "2026",
    "description": "Barsaat ma construction krne ka tareeqa. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-25",
    "videoId": "aiuvCz8Ub6o",
    "title": "Realestate krne ka sahi tareeka #realestateinvestment",
    "cleanTitle": "Realestate krne ka sahi tareeka",
    "views": "1.2K views",
    "society": "Wah Cantt",
    "category": "ADVISORY",
    "tag": "Market Advisory",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/aiuvCz8Ub6o/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/aiuvCz8Ub6o",
    "youtubeUrl": "https://www.youtube.com/shorts/aiuvCz8Ub6o",
    "publishedDate": "2026",
    "description": "Realestate krne ka sahi tareeka. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-26",
    "videoId": "gvzuswNdl1s",
    "title": "H block grey structure Kohistan enclave #realestateinvestment",
    "cleanTitle": "H block grey structure Kohistan enclave",
    "views": "1.2K views",
    "society": "Kohistan Enclave",
    "category": "CONSTRUCTION_TIPS",
    "tag": "Construction & Engineering",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/gvzuswNdl1s/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/gvzuswNdl1s",
    "youtubeUrl": "https://www.youtube.com/shorts/gvzuswNdl1s",
    "publishedDate": "2026",
    "description": "H block grey structure Kohistan enclave. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-27",
    "videoId": "bbIiHrNbhyU",
    "title": "13 Marla plot for sale in Kohistan enclave Wah cantt #plotsale",
    "cleanTitle": "13 Marla plot for sale in Kohistan enclave Wah cantt",
    "views": "839 views",
    "society": "Kohistan Enclave",
    "category": "PLOT_SALE",
    "tag": "Plot Deal",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/bbIiHrNbhyU/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/bbIiHrNbhyU",
    "youtubeUrl": "https://www.youtube.com/shorts/bbIiHrNbhyU",
    "publishedDate": "2026",
    "description": "13 Marla plot for sale in Kohistan enclave Wah cantt. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-28",
    "videoId": "k3TzA6pM-xk",
    "title": "Ghar bnaty hue sath walon ka b khayal krein #realestateinvestment",
    "cleanTitle": "Ghar bnaty hue sath walon ka b khayal krein",
    "views": "2.3K views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/k3TzA6pM-xk/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/k3TzA6pM-xk",
    "youtubeUrl": "https://www.youtube.com/shorts/k3TzA6pM-xk",
    "publishedDate": "2026",
    "description": "Ghar bnaty hue sath walon ka b khayal krein. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-29",
    "videoId": "t1lgiqTnazs",
    "title": "Ghar bnanay ka tareeka #realestateinvestment",
    "cleanTitle": "Ghar bnanay ka tareeka",
    "views": "886 views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/t1lgiqTnazs/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/t1lgiqTnazs",
    "youtubeUrl": "https://www.youtube.com/shorts/t1lgiqTnazs",
    "publishedDate": "2026",
    "description": "Ghar bnanay ka tareeka. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-30",
    "videoId": "2cMiUhO0hdo",
    "title": "House for sale In Kohistan enclave #realestateinvestment",
    "cleanTitle": "House for sale In Kohistan enclave",
    "views": "1.5K views",
    "society": "Kohistan Enclave",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/2cMiUhO0hdo/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/2cMiUhO0hdo",
    "youtubeUrl": "https://www.youtube.com/shorts/2cMiUhO0hdo",
    "publishedDate": "2026",
    "description": "House for sale In Kohistan enclave. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-31",
    "videoId": "nBQ2NAF5Ofw",
    "title": "House for sale #kohistanenclave",
    "cleanTitle": "House for sale",
    "views": "2.1K views",
    "society": "Kohistan Enclave",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/nBQ2NAF5Ofw/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/nBQ2NAF5Ofw",
    "youtubeUrl": "https://www.youtube.com/shorts/nBQ2NAF5Ofw",
    "publishedDate": "2026",
    "description": "House for sale. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-32",
    "videoId": "byeEY5Q13Ls",
    "title": "House for sale Kohistan enclave #realestateinvestment",
    "cleanTitle": "House for sale Kohistan enclave",
    "views": "43K views",
    "society": "Kohistan Enclave",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/byeEY5Q13Ls/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/byeEY5Q13Ls",
    "youtubeUrl": "https://www.youtube.com/shorts/byeEY5Q13Ls",
    "publishedDate": "2026",
    "description": "House for sale Kohistan enclave. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-33",
    "videoId": "CPcFC5P-RUQ",
    "title": "Achy ghar ki pehchaan #realestateinvestment",
    "cleanTitle": "Achy ghar ki pehchaan",
    "views": "3.1K views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/CPcFC5P-RUQ/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/CPcFC5P-RUQ",
    "youtubeUrl": "https://www.youtube.com/shorts/CPcFC5P-RUQ",
    "publishedDate": "2026",
    "description": "Achy ghar ki pehchaan. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-34",
    "videoId": "NnlouB0ESHw",
    "title": "Why Kohistan enclave is best #realestateinvestment",
    "cleanTitle": "Why Kohistan enclave is best",
    "views": "1.1K views",
    "society": "Kohistan Enclave",
    "category": "ADVISORY",
    "tag": "Market Advisory",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/NnlouB0ESHw/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/NnlouB0ESHw",
    "youtubeUrl": "https://www.youtube.com/shorts/NnlouB0ESHw",
    "publishedDate": "2026",
    "description": "Why Kohistan enclave is best. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-35",
    "videoId": "yxKGIn10Xgg",
    "title": "This is called Kohistan enclave #realestateinvestment",
    "cleanTitle": "This is called Kohistan enclave",
    "views": "1.1K views",
    "society": "Kohistan Enclave",
    "category": "ADVISORY",
    "tag": "Real Estate",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/yxKGIn10Xgg/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/yxKGIn10Xgg",
    "youtubeUrl": "https://www.youtube.com/shorts/yxKGIn10Xgg",
    "publishedDate": "2026",
    "description": "This is called Kohistan enclave. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-36",
    "videoId": "RnSKBdHhMUc",
    "title": "13 Marla site update #realestateinvestment",
    "cleanTitle": "13 Marla site update",
    "views": "1.5K views",
    "society": "Wah Cantt",
    "category": "ADVISORY",
    "tag": "Real Estate",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/RnSKBdHhMUc/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/RnSKBdHhMUc",
    "youtubeUrl": "https://www.youtube.com/shorts/RnSKBdHhMUc",
    "publishedDate": "2026",
    "description": "13 Marla site update. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-37",
    "videoId": "1WSejknHI-0",
    "title": "Ghar kese bnayein #realestateinvestment",
    "cleanTitle": "Ghar kese bnayein",
    "views": "4.4K views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/1WSejknHI-0/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/1WSejknHI-0",
    "youtubeUrl": "https://www.youtube.com/shorts/1WSejknHI-0",
    "publishedDate": "2026",
    "description": "Ghar kese bnayein. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-38",
    "videoId": "Ri5ho4QVuRs",
    "title": "Plot buying strategy #realestateinvestment",
    "cleanTitle": "Plot buying strategy",
    "views": "1.2K views",
    "society": "Wah Cantt",
    "category": "PLOT_SALE",
    "tag": "Plot Deal",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/Ri5ho4QVuRs/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/Ri5ho4QVuRs",
    "youtubeUrl": "https://www.youtube.com/shorts/Ri5ho4QVuRs",
    "publishedDate": "2026",
    "description": "Plot buying strategy. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-39",
    "videoId": "u6zJApoOHBc",
    "title": "Plenth beam dalne ka tareeka #realestateinvestment",
    "cleanTitle": "Plenth beam dalne ka tareeka",
    "views": "4.4K views",
    "society": "Wah Cantt",
    "category": "CONSTRUCTION_TIPS",
    "tag": "Construction & Engineering",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/u6zJApoOHBc/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/u6zJApoOHBc",
    "youtubeUrl": "https://www.youtube.com/shorts/u6zJApoOHBc",
    "publishedDate": "2026",
    "description": "Plenth beam dalne ka tareeka. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-40",
    "videoId": "EUL3XP8h1BY",
    "title": "Chunai krne ka best tareeka #realestateinvestment",
    "cleanTitle": "Chunai krne ka best tareeka",
    "views": "2.3K views",
    "society": "Wah Cantt",
    "category": "CONSTRUCTION_TIPS",
    "tag": "Construction & Engineering",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/EUL3XP8h1BY/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/EUL3XP8h1BY",
    "youtubeUrl": "https://www.youtube.com/shorts/EUL3XP8h1BY",
    "publishedDate": "2026",
    "description": "Chunai krne ka best tareeka. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-41",
    "videoId": "IIcGzSbKKMw",
    "title": "13 Marla plot for sale in Kohistan enclave #realestateinvestment",
    "cleanTitle": "13 Marla plot for sale in Kohistan enclave",
    "views": "918 views",
    "society": "Kohistan Enclave",
    "category": "PLOT_SALE",
    "tag": "Plot Deal",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/IIcGzSbKKMw/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/IIcGzSbKKMw",
    "youtubeUrl": "https://www.youtube.com/shorts/IIcGzSbKKMw",
    "publishedDate": "2026",
    "description": "13 Marla plot for sale in Kohistan enclave. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-42",
    "videoId": "SmSh9aaojBU",
    "title": "Kohistan enclave Wah cantt I block #realestateinvestment",
    "cleanTitle": "Kohistan enclave Wah cantt I block",
    "views": "3.1K views",
    "society": "Kohistan Enclave",
    "category": "ADVISORY",
    "tag": "Real Estate",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/SmSh9aaojBU/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/SmSh9aaojBU",
    "youtubeUrl": "https://www.youtube.com/shorts/SmSh9aaojBU",
    "publishedDate": "2026",
    "description": "Kohistan enclave Wah cantt I block. Practical ground reality insights, verified plot data and construction execution in Kohistan Enclave by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedSocietySlug": "kohistan-enclave-wah",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-43",
    "videoId": "2kRV0Ohpe_M",
    "title": "Column curing kese krein #realestateinvestment",
    "cleanTitle": "Column curing kese krein",
    "views": "1.9K views",
    "society": "Wah Cantt",
    "category": "CONSTRUCTION_TIPS",
    "tag": "Construction & Engineering",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/2kRV0Ohpe_M/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/2kRV0Ohpe_M",
    "youtubeUrl": "https://www.youtube.com/shorts/2kRV0Ohpe_M",
    "publishedDate": "2026",
    "description": "Column curing kese krein. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-44",
    "videoId": "UmFJQDmstmo",
    "title": "Columns asay bnao #realestateinvestment",
    "cleanTitle": "Columns asay bnao",
    "views": "3.4K views",
    "society": "Wah Cantt",
    "category": "CONSTRUCTION_TIPS",
    "tag": "Construction & Engineering",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/UmFJQDmstmo/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/UmFJQDmstmo",
    "youtubeUrl": "https://www.youtube.com/shorts/UmFJQDmstmo",
    "publishedDate": "2026",
    "description": "Columns asay bnao. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-45",
    "videoId": "u-xAxYoc5PA",
    "title": "Ghar bnanay ka tareeka #realestateinvestment",
    "cleanTitle": "Ghar bnanay ka tareeka",
    "views": "4K views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/u-xAxYoc5PA/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/u-xAxYoc5PA",
    "youtubeUrl": "https://www.youtube.com/shorts/u-xAxYoc5PA",
    "publishedDate": "2026",
    "description": "Ghar bnanay ka tareeka. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-46",
    "videoId": "Gx3z9MjP1bM",
    "title": "Marble dpc k opar kyun #realestateinvestment",
    "cleanTitle": "Marble dpc k opar kyun",
    "views": "25K views",
    "society": "Wah Cantt",
    "category": "CONSTRUCTION_TIPS",
    "tag": "Construction & Engineering",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/Gx3z9MjP1bM/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/Gx3z9MjP1bM",
    "youtubeUrl": "https://www.youtube.com/shorts/Gx3z9MjP1bM",
    "publishedDate": "2026",
    "description": "Marble dpc k opar kyun. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  },
  {
    "id": "short-47",
    "videoId": "KR2tvcLidOs",
    "title": "Ac ase lgao #realestateinvestment",
    "cleanTitle": "Ac ase lgao",
    "views": "6.3K views",
    "society": "Wah Cantt",
    "category": "ADVISORY",
    "tag": "Real Estate",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/KR2tvcLidOs/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/KR2tvcLidOs",
    "youtubeUrl": "https://www.youtube.com/shorts/KR2tvcLidOs",
    "publishedDate": "2026",
    "description": "Ac ase lgao. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-1"
  },
  {
    "id": "short-48",
    "videoId": "tEyW2101bKM",
    "title": "Ghar ko pehchanay ka tareeka #realestateinvestment",
    "cleanTitle": "Ghar ko pehchanay ka tareeka",
    "views": "4.1K views",
    "society": "Wah Cantt",
    "category": "HOUSE_TOUR",
    "tag": "House Tour",
    "duration": "00:59",
    "thumbnail": "https://i.ytimg.com/vi/tEyW2101bKM/hqdefault.jpg",
    "videoUrl": "https://www.youtube.com/embed/tEyW2101bKM",
    "youtubeUrl": "https://www.youtube.com/shorts/tEyW2101bKM",
    "publishedDate": "2026",
    "description": "Ghar ko pehchanay ka tareeka. Practical ground reality insights, verified plot data and construction execution in Wah Cantt by Asad Land Holdings.",
    "isShort": true,
    "aspectRatio": "9:16",
    "linkedPropertyId": "prop-2"
  }
];
